language: node_js
node_js: "stable"
before_install: 
  - bundle exec jekyll build
  - gem install scss-lint
  - gem install html-proofer
scripts: bundle exec jekyll build
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true