source: .
destination: _site
plugins: _plugins
layouts: _layouts

safe: true
lsi: false
pygments: true
markdown: kramdown

url: http://katydecorah.com
permalink: pretty

paginate: 7
paginate_path: ":num"

name: Katy DeCorah
description: "Front-end developer and instructional designer from Albany, NY."
image: https://farm6.staticflickr.com/5040/14020650339_3df5a63681_o.jpg

timezone: America/New_York

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

exclude: [vendor, node_modules, Gemfile, Gruntfile.js, package.json]

links:
- text: Hello
  url: /hello/
  position: top
- text: Archive
  url: /archive/
  icon: archive
  position: top
- text: Email
  url: mailto:katydecorah@gmail.com
  icon: envelope
  position: bottom
- text: CodePen
  url: http://codepen.io/katydecorah/
  icon: codepen
  position: bottom
- text: Twitter
  url: https://twitter.com/katydecorah
  icon: twitter
  position: bottom
- text: Instagram
  url: http://instagram.com/katydecorah
  icon: instagram
  position: bottom
- text: Feed
  url: /feed.xml
  icon: rss
  position: bottom
