port: 4000
host: 127.0.0.1

highlighter: pygments
markdown: kramdown

url: http://katydecorah.com
permalink: /:categories/:title
#permalink: pretty

paginate: 5
paginate_path: ":num"

name: Katy DeCorah
description: "Explainer, helper, and tinkerer from Albany, NY."
image: https://farm4.staticflickr.com/3786/14321547483_524b5cbce1_o.jpg


sass:
  style: :compressed

timezone: America/New_York

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

exclude: [vendor,CNAME,README.md]

links:
- text: Hello!
  url: /hello/
  position: top
- text: Card Catalog
  url: /card-catalog/
  position: top
- text: Time Capsule
  url: /time-capsule/
  icon: archive
  position: top

- text: CodePen
  url: http://codepen.io/katydecorah/
  icon: codepen
  position: bottom
- text: Github
  url: https://github.com/katydecorah
  icon: github-alt
  position: bottom
- text: Twitter
  url: https://twitter.com/katydecorah
  icon: twitter
  position: bottom
- text: Instagram
  url: http://instagram.com/katydecorah
  icon: instagram
  position: bottom
- text: Feed
  url: /feed.xml
  icon: rss
  position: bottom

mapbox-token: pk.eyJ1Ijoia2F0eWRlY29yYWgiLCJhIjoiNTNmZDUwOGRhMWU1MWI5Njg0MWVmYmFjZWRmNTgwZDMifQ.LcCTqgT1JdMpsVapPwPpmQ
mapid: katydecorah.21d6ba77
mapid-winter: katydecorah.70f1a6d1
mapboxjs: v2.2.2
font-awesome: 4.4.0

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
