source: .
destination: _site
plugins: _plugins
layouts: _layouts

lsi: false
highlighter: pygments
markdown: kramdown

url: http://katydecorah.com
permalink: pretty

paginate: 7
paginate_path: ":num"

name: Katy DeCorah
description: "Front-end developer, designer, and sometimes teacher from Albany, NY."
image: https://farm4.staticflickr.com/3786/14321547483_524b5cbce1_o.jpg

timezone: America/New_York

gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

exclude: [vendor, node_modules, Gemfile, Gruntfile.js, package.json]

links:
- text: Hello!
  url: /hello/
  position: top
- text: Card Catalog
  url: /card-catalog/
  position: top
- text: Time Capsule
  url: /time-capsule/
  icon: archive
  position: top
- text: Email
  url: mailto:katydecorah@gmail.com
  icon: envelope
  position: bottom
- text: CodePen
  url: http://codepen.io/katydecorah/
  icon: codepen
  position: bottom
- text: Twitter
  url: https://twitter.com/katydecorah
  icon: twitter
  position: bottom
- text: Instagram
  url: http://instagram.com/katydecorah
  icon: instagram
  position: bottom
- text: Feed
  url: /feed.xml
  icon: rss
  position: bottom

mapbox_token: pk.eyJ1Ijoia2F0eWRlY29yYWgiLCJhIjoibGQtZjZINCJ9.qrZnVyO9TghqkQDZPFFnPw
mapbox_mapid: katydecorah.h41bj3lj

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"