source: .
destination: _site
plugins: _plugins
layouts: _layouts

baseurl: http://katydecorah.com/
url: http://katydecorah.com/
permalink: pretty

paginate: 7
paginate_path: ":num"

name: Katy DeCorah
description: "Web developer, instructional designer, and adjunct professor from Albany, NY."
image: http://katydecorah.com/img/katy.png

timezone: America/New_York

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false