source: .
destination: _site
plugins: _plugins
layouts: _layouts

safe: true
lsi: false
pygments: true

baseurl: http://katydecorah.com/
url: http://katydecorah.com/

permalink: pretty

paginate: 7
paginate_path: ":num"

name: Katy DeCorah
description: "Web developer, instructional designer, and adjunct professor from Albany, NY."