source:      .
destination: _site
plugins:     _plugins
layouts:     _layouts

safe:        true
baseurl:     http://katydecorah.com/
url:         http://katydecorah.com/
lsi:         false

name: Katy DeCorah
description: Web developer, instructional designer, and adjunct professor from Albany, NY.